### ISSUE TITLE
setLanguageConfiguration

### ISSUE THREAD

**Issue by texastoland** [nwolverson/vscode-language-purescript#1]
Needed for contextual shortcuts (probably other stuff):
https://code.visualstudio.com/docs/extensionAPI/vscode-api#languages.setLanguageConfiguration

**Comment by nwolverson** [comment]
I don't believe this is required, I think this is a programmatic interface to configuration already present in the config

https://github.com/nwolverson/vscode-language-purescript/blob/master/package.json#L24

**Comment by texastoland** [comment]
You're right I was having trouble finding that 🙏
