### ISSUE TITLE
Integration with `purty`

### ISSUE THREAD

**Issue by joneshf** [nwolverson/vscode-language-purescript#10]
Howdy!

I maintain a source code formatter: [`purty`][]. I'd like to add support for [using it from VS Code][integration]. The goal here is that formatting PS code be dead simple (not many install steps, no extra binaries to download, etc.).

I'd like the burden on you to be as minimal as possible, so when the API of `purty` changes, I expect to update whatever's necessary to work here. Would it be easier if I maintained an extension and this extension depended on it somehow (I don't know enough about the VS Code ecosystem)? There is an extension [specifically for `purty`][vscode-purty], but its releases have some drift from [`purty`][]s. I'd like to minimize that as much as possible.

What are your thoughts?

[`purty`]: https://gitlab.com/joneshf/purty
[integration]: https://gitlab.com/joneshf/purty/issues/124
[vscode-purty]: https://marketplace.visualstudio.com/items?itemName=mvakula.vscode-purty

**Comment by mvakula** [comment]
If needed I can make a PR for purty support here.

P.S. I also updated and published [vscode-purty extension](https://marketplace.visualstudio.com/items?itemName=mvakula.vscode-purty) to work with the latest purty release.

**Comment by nwolverson** [comment]
Certainly my feeling is that a separate extension doing code formatting is a good thing. I don't think this extension should depend on it, as it is just the bare minimum syntax highlighting etc.

I thought that there was a way to recommend extensions, but it only seems to be per workspace not as a weak dependency of an extension? Possibly could add a dependency to [ide-purescript](https://github.com/nwolverson/vscode-ide-purescript) which is already kitchen sink

**Comment by nwolverson** [comment]
At a bare minimum if someone wants to PR the readmes of this and ide-purescript before I get around to it, please do

**Comment by nwolverson** [comment]
Code formatting via purty is now provided via the purescript-language-server (or the extension linked previously) so I don't think this issue is relevant any more.
