### ISSUE TITLE
Publish extension on Open VSX registry

### ISSUE THREAD

**Issue by sigma-andex** [nwolverson/vscode-language-purescript#23]
Would it be possible to publish this extension on the [Open VSX Registry](https://open-vsx.org/)?

I have created a similar issue for [vscode-ide-purescript](https://github.com/nwolverson/vscode-ide-purescript/issues/183)

**Comment by nwolverson** [comment]
This is now published from CI as is the IDE extension https://open-vsx.org/extension/nwolverson/language-purescript
