### ISSUE TITLE
Add syntax snippets

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-language-purescript#4]
Port from https://github.com/purescript-contrib/atom-language-purescript/blob/master/snippets/language-purescript.cson

**Comment by nwolverson** [comment]
Fixed by 6056b61535e657065e553159d12e317fb3f48143

**Comment by spicydonuts** [comment]
Amazing, thank you!

(it's at the bottom for some reason but it's selected by default so it works just fine)

<img width="733" alt="psc-ide-do-fixed" src="https://cloud.githubusercontent.com/assets/715921/21527118/2185944c-cce6-11e6-833e-3dcc1ac65e0a.png">
