### ISSUE TITLE
Working with Pursuit comments

### ISSUE THREAD

**Issue by karljs** [nwolverson/vscode-language-purescript#6]
Pursuit uses the special comment syntax `-- | Comment here`.  This should probably be treated specially so that it doesn't lead to weird behavior when, for example, re-wrapping text.  If I have something like:

```
-- | some text.
-- | a long line of stuff here.
```

and I wrap the text (using vscode-vim (`gqap` for example) or another plugin that does this specifically) then I get the following:

```
-- | some text. | a long line
-- of stuff here.
```

rather than:

```
-- | some text.  a long line
-- | of stuff here.
```

**Comment by nwolverson** [comment]
How does your plugin do text wrapping?

vscode does not provide the ability to define more than one line comment syntax https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages

But actually looks to me like the comment syntax is hardcoded in vscode-vim: https://github.com/VSCodeVim/Vim/blob/master/src/actions/operator.ts#L726

**Comment by karljs** [comment]
@nwolverson Thanks for the response.  I didn't realize vscode-vim hardcoded everything, and the other approach I tried (the [rewrap plugin](https://github.com/stkb/Rewrap)) takes the same approach.  I assumed there was some kind of universal way to define this.  I'll close the issue here.
