### ISSUE TITLE
Cmd+d in string literals selects quotation mark

### ISSUE THREAD

**Issue by dktn** [nwolverson/vscode-language-purescript#7]
Cmd+d in string literals selects quotation mark, for example in `"abc def"` will select `"abc` or `def"` depending on where was the cursor. To fix this I've changed wordPattern from:
`wordPattern: /\\[^\s]+|[^\\\s\d(){}\[\]#.][^\\\s(){}\[\]#.]*/`
to
`wordPattern: /\\[^\s]+|[^\\\s\d\"'(){}\[\]#.][^\\\s\"'(){}\[\]#.]*/`
If the original behaviour wasn't intentional I would suggest to change it in official version. Most of other language plugins don't include quotation marks when selecting words, including Haskell one.

**Comment by dktn** [comment]
After a while I completely switched to Haskell plugin version:
`wordPattern: /([\w'_][\w'_\d]*)|([0-9]+\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+)/`
It handles also backticks, colons, semicolons etc. as expected, i.e. excluding them from the selection.

**Comment by nwolverson** [comment]
Don't see any reason we'd have to deviate from Haskell if it works well, there are no language differences here I think?

**Comment by nwolverson** [comment]
Made the suggested change 6373b835af1aaa4630c3fb8aedf2659aac669e43.
